main:
  params: [args]
  steps:
    - init:
        assign:
          - location: ${args.location}
          - project: ${args.project_id}
          - entrypoint: ${args.entrypoint}
          - query: ${args.query}
    - call:
        try:
          call: http.get
          args:
            url: ${"https://" + location + "-" + project +".cloudfunctions.net/" + entrypoint }
            auth:
              type: OAuth2
            query: ${query}
          result: result
        except:
          as: e
          steps:
            - raise_exception:
                raise: ${e}
    - format_log:
        assign:
          - response: ${result.body}
    - log:
        call: sys.log
        args:
          text: ${json.encode_to_string(response)}
          severity: INFO
    - exit:
        return: ${response}