main:
  params: [args]
  steps:
    - init:
        assign:
          - project: ${args.projectId}
          - query: ${args.query}
    - call:
        try:
          call: http.post
          args:
            url: ${ "https://bigquery.googleapis.com/bigquery/v2/projects/"+project+"/queries" }
            auth:
              type: OAuth2
            body: ${query}
          result: result
        except:
          as: e
          steps:
            - raise_exception:
                raise: ${e.body}
    - format_log:
        assign:
          - response: ${result.body}
    - log:
        call: sys.log
        args:
          text: ${json.encode_to_string(response)}
          severity: INFO
    - exit:
        return: ${response}